### ISSUE TITLE
Change searge mappings to MCP mappings

### ISSUE THREAD

**Issue by Four44Four** [Torono909/UwUGod-Modules-Src#1]
Use these files attached to turn the searge mappings into MCP mappings (eg.   field_110153_bc   ->   lastDamage) since people can't skid properly if they don't know what any of the methods or variables do. (and since this is literally just the decompiled jar that anyone can see if they open the original jar in intellij so doing this would make this repo a bit more useful)
[fields.csv](https://github.com/Torono909/UwUGod-Modules-Src/files/8405595/fields.csv)
[methods.csv](https://github.com/Torono909/UwUGod-Modules-Src/files/8405596/methods.csv)
[params.csv](https://github.com/Torono909/UwUGod-Modules-Src/files/8405597/params.csv)

**Comment by ghost** [comment]
wat the fawk

**Comment by Tarkan-Zarrouk** [comment]
Torono has brain damage, he aint gon do shit 💀

**Comment by Four44Four** [comment]
💀

**Comment by ghost** [comment]
> Torono has brain damage, he aint gon do shit skull

true
